# These are supported funding model platforms

custom: 
Sponsor pennyblogs by supporting my blog - https://read.cash/@Knopodters

Also, you can help supply liquidity or crowdsale tokens to support the app, more info on the website:

https://pennyblog.netlify.app/

Twitter: Support via Follow the socials@ like twitter, this is a great source of exposure.

https://twitter.com/GummerMon

